Remove incorrect working path of workflow (#2)
* Remove incorrect working path of workflow

* Add checkstyle.xml

* Make it compile

* Collect the build result

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,7 @@ on:
     branches:
       - master
 jobs:
-  build:
+  maven-build:
     name: "${{ matrix.os }}, jdk-${{ matrix.jdk }}"
     runs-on: ${{ matrix.os }}
     strategy:
@@ -23,8 +23,20 @@ jobs:
           distribution: "adopt"
           cache: maven
       - name: Build with Maven
-        working-directory: ./java
         run: mvn -B package --file pom.xml
-      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-      - name: Update dependency graph
-        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+  build-result:
+    runs-on: ubuntu-latest
+    needs: [maven-build]
+    if: ${{ always() }}
+    steps:
+      - uses: actions/checkout@v2
+      - name: Collect build result
+        run: |
+          if echo ${{ needs.maven-build.result }} | grep -E 'cancelled|failure' -o > null
+          then
+            echo "There are failed/cancelled builds"
+            exit 1 
+          else
+            echo "All builds are successful/skipped"
+            exit 0
+          fi
